bitly/oauth2_proxy

main.go, oauthproxy.go, options.go
Sample Command to run multi whitelisted urls with regex.
./google_auth_proxy \
--redirect-url="http://yourcallbackurl.com/oauth2/callback"  \
--google-apps-domain="yourdomain.com" \
--upstream=http://127.0.0.1:8080 \
--cookie-secret="nuts"\
--client-id="your client id" \
--client-secret="your client secret"  \
--cookie-expire=0h30m0s \
--cookie-https-only=false \
--skip-auth-regex="/hello.php","/status.php","/health-check-url/*"
=> Support for multi white listed urls with regex url match.

README.md, main.go
Can now listen for HTTP clients on unix sockets (and any other Go-supported stream oriented network, see http://golang.org/pkg/net/#Listen).  Default behaviour is unchanged, any http-address without a scheme is given the default value of "tcp".
Amended the README so that the usage output is up to date.
=> Added scheme parsing to http-address param

options.go, options_test.go
Notice that the existing `Options.Validate()` has a bug: if the cookie secret is empty, the error doesn't actually get raised.
=> Catch more options errors at once; add test

.travis.yml, README.md, contrib/google_auth_proxy.cfg.example, main.go, oauthproxy.go, oauthproxy_test.go, options.go, options_test.go
This extends the work in #45 to add an option for using the request Host Header or upstream host as Host Header for upstream requests.
=> Proxied requests use the upstream Host as Host Header

oauthproxy.go, oauthproxy_test.go
To reproduce, hit this URL on the proxy: `http://proxy/a%2Fb/`
It is passed to the backend as `http://backend/a/b/`
The expected result is for the backend to receive `http://backend/a%2Fb/`
This is a problem for Jenkins and is described here: https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+says+my+reverse+proxy+setup+is+broken
=> Encoded slashes are expanded by the proxy

README.md, contrib/google_auth_proxy.cfg.example, oauthproxy.go, options.go
This constructs a default redirect-url using "http://" + request host header + "/oauth2/callback". This enables easy ability to secure multiple virtual hosts w/ the same GAP instance as outlined in #51
=> make redirect-uri optional

README.md, contrib/google_auth_proxy.cfg.example, main.go, oauthproxy.go, options.go
This adds a new --cookie-secure option to replace --cookie-https-only which was became confusing after a flag for httponly was added.
This replaces #59
=> Rename flag to set secure (https) cookies

README.md, contrib/google_auth_proxy.cfg.example, logging_handler.go, main.go, oauthproxy.go, options.go
This improves request logging from
```
2015/03/19 20:13:41 127.0.0.1:55370 GET /path/
```
To something closer to Apache Common Log format which includes the Host requested, response code, upstream response timings, etc
```
<REMOTE_ADDRESS> - <user@domain.com> [19/Mar/2015:17:20:19 -0400] <HOST_HEADER> GET <UPSTREAM_HOST> "/path/" HTTP/1.1 "<USER_AGENT>" <RESPONSE_CODE> <RESPONSE_BYTES> <REQUEST_DURATION>
```
=> Request Logging:

oauthproxy.go, oauthproxy_test.go
This looks like a regression in 1.1.
When I request `/` through the proxy, the upstream receives:
```
GET http://127.0.0.1:8000/ HTTP/1.1
```
The expected request would be:
```
GET / HTTP/1.1
```
=> request path contains full URL

api/api.go, api/api_test.go, oauthproxy.go
This is the first step towards genericizing the google_auth_proxy to support
OAuth2 providers other than Google as discussed in #65. The `api` package will
enable multiple providers to use the same `api.Request()` implementation.
=> Extract api package

main.go, oauthproxy.go, options.go, options_test.go, providers/google.go, providers/google_test.go, providers/provider_data.go, providers/providers.go
This is the second step towards genericizing the google_auth_proxy to support
OAuth2 providers other than Google as discussed in #65. This builds upon #76 to introduce a generic `Provider` interface and to extract Google-specific implementation details into a `GoogleProvider`.
=> Extract providers package

oauthproxy.go, providers/google.go, providers/google_test.go, providers/provider_data.go, templates.go
This is the third step towards genericizing the google_auth_proxy to support OAuth2 providers other than Google as discussed in #65. Injecting the `ProviderName` into the template seems the most expedient way to reuse the default `sign_in.html` template.
Also, @jehiah, I was wondering: If you want, I can follow this PR with a PR to rename the service to `oauth2_proxy`. Otherwise, I'll go ahead and send a PR to add the MyUSA provider (plus README updates on how to add a new provider).
=> Add ProviderName field; use in sign_in template

README.md, providers/myusa.go, providers/myusa_test.go, providers/providers.go
This adds MyUSA as the first non-Google OAuth2 provider as discussed in #65.
cc: @balshor @adelevie @yozlet @jackiekazil
=> Add myusa provider

README.md, cookies.go, cookies_test.go, main.go, oauthproxy.go, oauthproxy_test.go, options.go
@jehiah We're looking to allow other services that accept the `access_token` to be integrated into the 18F Hub per 18F/hub#241. This PR accomplishes this by encoding the `access_token` in the auth cookie and unpacking it as the `X-Forwarded-Access-Token` header for upstream requests. The changes maintain backward compatibility with the original cookie format, but I'm happy to entertain other notions or refactor the code.
@dhcole @afeld @adelevie @yozlet @jackiekazil I've actually got our internal Hub running successfully with these changes to the `google_auth_proxy` and the changes from 18F/hub#241. Just need to merge them to make them official.
I also included a commit to update TestNewReverseProxy(). Without this change, the test will fail when run without an Internet connection. …
=> Pass the access token to the upstream server

oauthproxy.go, oauthproxy_test.go
Without this change, clicking the sign-in button on `/oauth2/sign_in` will always redirect back to `/oauth2/sign_in`, essentially creating an infinite loop.
@adelevie @esgoodman @dhcole: I've pushed an instance to the Hub with this feature integrated, and thanks to a comedy of errors, I've already pushed the "Log Out" link to the Hub as well (before issuing a PR as I'd intended). Long and short of it is, there's a working "Log Out" link on the Hub now. :-)
=> Redirect to / when /oauth2/sign_in accessed

.gitignore, cookies.go, cookies_test.go, oauthproxy.go, oauthproxy_test.go, options.go, options_test.go
This attempts to better encapsulate the changes from #80 and adds some more tests.
=> Refactor pass_access_token changes from #80

validator.go, validator_test.go
=> Make address/domain comparisons case-insensitive

README.md, providers/linkedin.go, providers/linkedin_test.go, providers/providers.go
The modifications from #79 made this much cleaner than last time.  Thanks for the refactoring and tests, @mbland!
=> Add LinkedIn provider

README.md, oauthproxy.go, oauthproxy_test.go
All the trawling through logs as part of #88 and #89 made me think a `/robots.txt` endpoint might be useful. ;-)
cc: @jehiah
=> Provide a robots.txt that denies all crawlers

README.md, contrib/google_auth_proxy.cfg.example, cookies.go, main.go, oauthproxy.go, oauthproxy_test.go, options.go, options_test.go, providers/google.go, providers/google_test.go, providers/myusa.go, providers/myusa_test.go, providers/provider_data.go
Hi @jehiah, at the prompting of a non-technical colleague at work (@lsgitter) and after being inspired by an idea from @adelevie, I've taken a stab at a new `cookie-refresh` flag. The idea is that the cookie's expiration date would automatically get updated whenever the user accesses an authenticated page within some window of time before it expires.
As you'll see, the first three commits are all refactorings; the one after that adds a test for the existing behavior; and the final commit is where the `cookie-refresh` feature is added.
Good idea? Bad idea?
=> Auto refresh auth token

Godeps, api/api_test.go, htpasswd.go, validator.go, validator_test.go, validator_watcher_copy_test.go, validator_watcher_test.go, watcher.go, watcher_unsupported.go
Closes #41.
The tricky part here is that sometimes popping the file open in an editor and writing to it results not in a direct write, but in some kind of remove and/or rename operation. (At least, that's how Vim appears to roll.) I've confirmed that this works on our running instance, regardless of whether the file is updated in a text editor or, in our case, regenerated via Jekyll (which, oddly, results in a write event, not a remove/rename). Will test out on various Linux flavors and Windows 8.1 a little later today.
cc: @jehiah @razb
=> Reload authenticated-emails-file upon update

validator.go, validator_test.go, validator_watcher_copy_test.go, validator_watcher_test.go, watcher.go
This test failure from #92 inspired this change:
https://travis-ci.org/bitly/google_auth_proxy/jobs/62425336
2015/05/13 16:27:33 using authenticated emails file /tmp/test_auth_emails_952353477
2015/05/13 16:27:33 watching /tmp/test_auth_emails_952353477 for updates
2015/05/13 16:27:33 validating: is xyzzy@example.com valid? true
2015/05/13 16:27:33 watching interrupted on event: "/tmp/test_auth_emails_952353477": CHMOD
2015/05/13 16:27:33 watching resumed for /tmp/test_auth_emails_952353477
2015/05/13 16:27:33 reloading after event: "/tmp/test_auth_emails_952353477": CHMOD
2015/05/13 16:27:33 watching interrupted on event: "/tmp/test_auth_emails_952353477": REMOVE
2015/05/13 16:27:33 validating: is xyzzy@example.com valid? false
2015/05/13 16:27:33 watching resumed for …
=> Provide graceful shutdown of file watcher in tests

.gitignore, README.md, dist.sh, main.go, oauthproxy.go, oauthproxy_test.go, options.go, providers/internal_util.go, providers/linkedin.go, providers/myusa.go, templates.go
Thanks @balshor @mbland for prompting changes to make the "Google" in "Google Auth Proxy" less relevant. It's high time to rename this project to something more generic.
I've had a few ideas, but i want to open this up to see what ideas anyone else has.
* `GAP` - I'm not sure who started the acronym version of the name but it's stuck. We could just stick with that and remove it's expanded meaning. (if anyone asks we can just say it stood for GreatAuthProxy all along :wink:)
* `AuthProxy` while descriptive, seems too generic
* `OAuthProxy` surprisingly googleable.
* other ideas?
=> Naming Is Hard - project name change

validator_watcher_copy_test.go, validator_watcher_test.go, watcher.go, watcher_unsupported.go
Closes #105.
The `go1.1` constraint has been updated to `!go1.3` per https://golang.org/pkg/go/build/#hdr-Build_Constraints and https://github.com/go-fsnotify/fsnotify. Also, the existing call signature for `WatchForUpdates()` in `watcher_unsupported.go` was stale.
Perhaps I'll take a stab at installing Plan 9 and Solaris virtual machines over the weekend. :-)
cc: @jehiah @dbiswas1
=> Fix unsupported WatchForUpdates and build tags

validator.go, watcher.go, watcher_unsupported.go
On these platforms, the `done <- true` statement in during TearDown() was hanging, since the `watcher_unsupported.go` version was never draining the channel. Also took the opportunity to update the WatchForUpdates() signature to not return bool anymore.
I developed this on Solaris 11 running in a VM, and confirmed that it's compatible with OS X. I'll expect it'll work just as well with Linux and Windows, and am trying to figure out how to get Go set up on Plan 9 as we speak.
cc: @jehiah
=> Fix validator_test hang on Solaris, Plan 9

README.md, contrib/oauth2_proxy.cfg.example, main.go, oauthproxy.go, options.go, validator.go
Hi, 
I'm using this great tool with an internal OAuth2 provider, in my case I want to authorize access to all authenticated users without any needed validation based on the email address.
Is there currently a way to disable email validation ?
I was thinking to implement pluggable validation system in the same way than the providers, does it sounds good to you ?
=> disable email validation

providers/github.go
I'm having trouble trying out oauth2 proxy with the Github provider as well. I'm able to get to the Github login page, log in, and then get redirected to the callback, but then I end up at this page:
The URL looks like:
`https://myapp.com/oauth2/callback?code=<some_code>&state=%2Foauth2`
Here's my configuration
```ini
request_logging = true
client_id = "<client_id>"
client_secret = "<client_secret>"
cookie_secret = "fadlkfjdlkaksfldkasfad"
provider = "github"
upstreams = [
"http://127.0.0.1:8080/"
]
```
And logs
```
2015/06/05 20:28:46 oauthproxy.go:121: Cookie settings: secure (https):true httponly:true expiry:168h0m0s domain:<default>
2015/06/05 20:28:46 main.go:128: listening on 127.0.0.1:4180
2015/06/05 20:29:02 oauthproxy.go:260: http: named cookie not present
104.218.136.246 - - …
```
=> Github provider "Invalid Account"

README.md, api/api.go, oauthproxy.go, providers/github.go, providers/internal_util.go, providers/provider_default.go, providers/providers.go
Hi,
Thanks for solving the previous request as i said i am very new to GO, my aim is to have Nginx authenticate via github
as of now i have nginx serving only the default home page, have enabled self signed certificate to test the authentication
my nginx config is as follows
server {
listen 80 default_server;
listen [::]:80 default_server ipv6only=on;
listen 443 ssl;
server_name ec2-52-25-160-240.us-west-2.compute.amazonaws.com;
root /usr/share/nginx/html;
index index.html index.htm;
ssl_certificate /etc/nginx/ssl/nginx.crt;
ssl_certificate_key /etc/nginx/ssl/nginx.key;
add_header Strict-Transport-Security max-age=1209600;
location / {
proxy_pass http://127.0.0.1:4180;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Scheme $scheme; …
=> Page defaults to Google sign in

README.md, contrib/oauth2_proxy.cfg.example, http.go, main.go, oauthproxy.go, options.go
Configuration steps would be much simpler if oauth2_proxy supported direct SSL configuration. This would make ssl termination with Nginx the "advanced" configuration.
=> Native SSL support

contrib/oauth2_proxy.cfg.example, cookies.go, oauthproxy.go, oauthproxy_test.go, providers/internal_util.go
I experienced a few issues with the current cookie refresh handling, that left me puzzled, but primarily i got a an empty cookie when a refresh should have happened.
This refactors that code a bit to fix that, and switches the timeframe for renewal to be since a cookie was set. (which i think is simpler to understand). Since the requirements (less than expiry) didn't change i think this is ok.
cc: @mbland
=> Cookie Refresh Improvements

README.md, main.go, oauthproxy.go, options_test.go, providers/google.go, providers/google_test.go, providers/provider_default.go, validator.go
Currently the Google provider uses an `online` token which expires in 60 minutes. This means that the token is not valid when passed to upstreams for some duration of time, and that it's not possible to refresh the cookie for a new duration (because the token expires and can't be revalidated).
The good news, refreshing a token does ensure that the token is valid. The bad news, with the google provider sessions fail when a refresh is attempted >1hr after cookie set.
=> Google - use offline access token

oauthproxy.go
I believe this small change handles #125.
=> Check email validity on all requests rather than only on login.

options.go, options_test.go, providers/github.go, providers/linkedin.go, validator.go
oauth2_proxy will return 500 to client after got 404 from github api as `error redeeming code got 404 from "https://api.github.com/user/emails?access_token=304d6bd5258b386fef07d9508808f8cd2b795528" {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}` . 
oauth2_proxy request log:
```
2015/07/20 19:01:07 oauthproxy.go:90: mapping path "/" => upstream "http://backend1:16087"
2015/07/20 19:01:07 oauthproxy.go:106: OauthProxy configured for GitHub Client ID: ****
2015/07/20 19:01:07 oauthproxy.go:116: Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domain:<default> refresh:after 1h0m0s
2015/07/20 19:01:07 http.go:45: HTTP: listening on 127.0.0.1:4180
2015/07/20 19:01:46 oauthproxy.go:455: 127.0.0.1:56904 ("123.116.156.176") Cookie …
```
=> provider github not work with scope read:org 

Godeps, README.md, main.go, oauthproxy.go, options.go, options_test.go, providers/google.go, providers/google_test.go, providers/provider_default.go, providers/providers.go
This change should be backwards compatible and only when you pass the three new flags will Google group validation happen.
partially implements features requested in #28 ( getting a list of all groups a user is a member of does not seems to be a single api call and would require listing all groups and then for all groups, querying the group to see if the user is in that group )
potential future improvements (not planned for this PR)
* support orgunits
=> [RDY] google: Support restricting access to a specific group(s)

README.md, main.go, oauthproxy.go, oauthproxy_test.go
As discussed in #141, this adds the possibility of hosting static files with oauth2_proxy.
The path should be provided as a file:/// url with the full operating system path, ie. `file:///var/www/static/`.
An alias to where the directory is available as can be specified by appending a fragment (ie. "#/static/") at the end of the URL, otherwise the full file path has to be entered in the URL when requesting the files.
Let me know if you have any comments on this. If not then I'll try to get it added to the README file.
=> Add support for serving static files from a directory

oauthproxy.go
The default `error.html` uses `ProxyPrefix` but it isn't supplied in the context, causing it to render incompletely:
=> Pass `ProxyPrefix` into the error template.

README.md, oauthproxy.go, oauthproxy_test.go
=> Add /auth endpoint to support Nginx's auth_request

validator.go, validator_test.go
Got burned by this one: trailing spaces in the authorized e-mail list would cause a mismatch when a user attempted to log in. This PR trims any spaces from the file.
=> Ignore spaces in authorized emails list

README.md, providers/github.go
Pull request to resolve issue "Custom github url not supported #144"
I removed hard-coded github.com endpoints. With the proposed changes oauth2_proxy works with enterprise github if user sets validateURL (as well as loginURL and redeemURL) to github enterprise endpoint.
=> use Github provider with GitHub enterprise

README.md, providers/gitlab.go, providers/gitlab_test.go, providers/providers.go
Works with either Gitlab.com or self-hosted GitLab instances.
Closes #200.
=> Add GitLab provider

README.md, options.go
Should've been part of #147. Motivated to add it by the Dockerization I'm performing in [18F/knowledge-sharing-toolkit](https://github.com/18F/knowledge-sharing-toolkit/).
cc: @jehiah @jcscottiii @mzia @NoahKunin @afeld @jmcarp @ccostino @ertzeid @mtorres253
=> OAUTH2_PROXY_SIGNATURE_KEY env var, README update

.travis.yml
was able to reproduce this locally, but not with 1.5.4 and 1.6.2.
This has affected builds since https://github.com/bitly/oauth2_proxy/pull/247, although I found out because my local build (on 1.6.2) worked before I pushed https://github.com/bitly/oauth2_proxy/pull/248
=> fix master build by upgrading with supported golang versions

dist.sh
Resolves this error:
mktemp: too few X's in template ‘oauth2_proxy’
=> fix dist.sh compatibility with GNU coreutils mktemp

main.go, oauthproxy.go, options.go
An option to skip the sign_in page and redirect instead to the start page.
That change is for users experience only. My users are fully aware that they will use their google account. They want to avoid any extra steps.
=> adding option to skip provider button sign_in page

cookie/cookies.go, cookie/cookies_test.go, main.go, oauthproxy.go, oauthproxy_test.go, options.go, options_test.go, providers/github.go, providers/session_state_test.go
What sort of encoding is expected for the cookie secret value?  It looks like the validate test is counting the number of characters (16, 24, or 32) in the string but I'm not sure how that relates to the number of bytes represented by the string.
If the encoding was urlsafe base64 a 32 byte string would look like this:
```
GOW9RCRecupnZ7cgGy9wMEGZ3Ssm2SpyAFUx_olbU90=
```
This string is 44 characters with the padding.  Each character represents 6 bits so we need all the bits from the first 42 characters and then 4 bits from the 43rd character, and then the rest is padding.
How are we getting 32 characters == 32 bytes?
=> Cookie secret encoding?

README.md, providers/github.go
This fixes github enterprise support originally added in #197 and closes #144 and #248
=> github enterprise provider

contrib/oauth2_proxy.service.example
Using -config="path" will make the application try to open paths with the quotes included which is not what is expected.
```
main.go:89: ERROR: failed to load config file "/etc/oauth2_proxy.cfg" - open "/etc/oauth2_proxy.cfg": no such file or directory
```
=> Remove superfluous quotes from config path

templates.go
This allows a seamless transition for applications that encode
state in the fragment.
=> Add URL fragment to sign-in form

README.md
The correct endpoint is /oauth2/auth
=> Fix documentation for auth_request directive

providers/azure.go, providers/azure_test.go
Updated Azure provider to fix Issue #232
=> Getting mail for Azure provider fix + tests

README.md
Addresses @ploxiln comment, closes issue #226.
Working & tested -- though auth_request is very limited without PR #247 and PR #173
Signed-off-by: Nick Semenkovich <semenko@alum.mit.edu>
=> Update docs for full working nginx auth_request example

options.go, options_test.go
This fixes #264 
`(http.Cookie).String()` will silently return an empty string when the cookie name contains a rune not in the following table https://github.com/golang/net/blob/master/lex/httplex/httplex.go#L17
With this patch I've added an additional validator to check the cookie name at boot. I've had to 'mock' a `http.Cookie` as the http package doesn't export the check function, here: https://github.com/golang/go/blob/master/src/net/http/cookie.go#L368
Regards,
James
=> Validate cookie name 

providers/github.go, providers/internal_util.go, providers/internal_util_test.go
Resolves #291 
After searching through the providers package manually, I determined the GitHub provider and `validateToken` helper function were the only areas at risk here. Other providers, like Google, encode their sensitive parameters as a form-encoded body, and they are never logged.
@jehiah
=> Strip sensitive URL parameters from provider log output

Godeps
This updates our godep version of `golang.org/x/oauth2/google` to track the upstream repository move.
cf.
https://github.com/golang/oauth2/commit/04e1573abc896e70388bd387a69753c378d46466
=> repo golang.org/x/oauth2/google has moved, fixes travis build

README.md
This pull request corrects the spelling of **GitHub** 🤓
https://github.com/
Created with [`readme-correct`](https://github.com/dkhamsing/readme-correct).
=> Correct the spelling of GitHub in README

dist.sh
fixes #353 
```
oauth2_proxy]$ tar -tvf dist/oauth2_proxy-2.2.0-alpha.windows-amd64.go1.8.tar.gz 
drwxr-xr-x  0 pierce staff       0 Mar 27 14:43 oauth2_proxy-2.2.0-alpha.windows-amd64.go1.8/
-rwxr-xr-x  0 pierce staff 12162048 Mar 27 14:43 oauth2_proxy-2.2.0-alpha.windows-amd64.go1.8/oauth2_proxy.exe
```
cc @Esfera5
=> dist.sh: add .exe for windows build

.travis.yml, Godeps, dist.sh
I ran into some problems running dist.sh on my system (OS X 10.11, go-1.8, gpm-1.4.0, git-2.12.1).
```
>> Setting github.com/18F/hmacauth to version 1.0.1
/usr/local/bin/gpm: line 73: cd: /Users/pierce/scratch/oauth2_proxy/.godeps/src/github.com/18F/hmacauth: No such file or directory
>> Setting github.com/BurntSushi/toml to version 3883ac1ce943878302255f538fce319d23226223
/usr/local/bin/gpm: line 73: cd: /Users/pierce/scratch/oauth2_proxy/.godeps/src/github.com
(... repeated for all deps, not a showstopper, build succeeds)
```
```
>> Setting golang.org/x/oauth2 to version 04e1573abc896e70388bd387a69753c378d46466
>> Setting golang.org/x/oauth2/google to version 04e1573abc896e70388bd387a69753c378d46466
>> Setting google.golang.org/api/admin/directory/v1 to version …
```
=> dist.sh and Godeps updates

oauthproxy.go, providers/provider_default.go
The current parsing of the "rd" and "state" query parameters allow for an open redirect, if the rd values is of the form `//domain.com/`.
Fixes #228
=> Improve redirect checks

providers/google.go
When checking user membership against Google groups the groups are checked one
at a time and in the order that they were supplied. If one of the groups does
not exist then the checking is halted with the following error.
google.go:201: googleapi: Error 404: Resource Not Found: groupKey, notFound
None of the groups following the missing group are checked either. This means
that something as trivial as a typo in the first group will make it impossible
for anybody to login.
This change catches the 404, logs a message, and then carries on as usual. In
this way a typo will cause a particular group to stop working but will not
affect any other groups.
=> Skip 404 errors when looking up Google groups

oauthproxy.go
Cookies cannot be larger than 4kb
It took me a long while to debug this, no one else should ever have to.
This issue showed face whilst attempting to add `refresh_token` support to the Azure provider, which uses pretty large tokens.
With all the padding and what not, I was hitting 4264 bytes, which was simply triggering the alert:
`Cookie "oauth2_proxy" not present`
=> Oversize Cookie Alert

README.md, contrib/oauth2_proxy.cfg.example, main.go, oauthproxy.go, oauthproxy_test.go, options.go
* This fixes https://github.com/bitly/oauth2_proxy/issues/205
* Add new boolean option -pass-user-headers
to control whether X-Forwarded-User and X-Forwarded-Email
headers will be set (as opposed to HTTP BASIC auth)
* This is required e.g. for grafana [1] where
X-Forwarded-User is needed but HTTP BASIC auth fails
(password is not known and must not be known in this scenario)
* Keep behaviour of PassBasicAuth unchanged for compatibility
[1] http://docs.grafana.org/installation/configuration/#authproxy
=> Allow to pass user headers only

cookie/nonce.go, oauthproxy.go, oauthproxy_test.go, providers/provider_default.go
This implements CSRF protection for the initiation and termination of the OAuth flow. (thanks @arnottcr and @therook for the contribution).
Fixes #336, #321
=> CSRF protection for OAuth flow.

README.md, contrib/oauth2_proxy.cfg.example, main.go, options.go
This adds an option to skip SSL verification which is useful when using oauth2_proxy in a development environment, or against a provider with a self-signed certificate.
This fixes #350, #234
=> Option to skip SSL verification

README.md, main.go, oauthproxy.go, oauthproxy_test.go, options.go
This supersedes #173 and #247, with the following changes:
- adds a new flag `--set-xauthrequest` which sets response headers for use in auth_request mode (analogous to the `X-Forwarded-User` and `X-Forwarded-Email` headers in normal mode).
- optionally read the redirect URL from request header `X-Auth-Request-Redirect` as the request URL doesn't correspond to the URL to redirect to in auth_request mode
- documentation updates
=> various fixes for getting Nginx auth_request mode working

README.md, main.go, oauthproxy.go, oauthproxy_test.go, options.go
* please see #369 for details
* this PR adds an option to allow skipping authentication for preflight requests
=> #369: Optionally allow skipping authentication for preflight requests

http.go
Fixes this error which I was running into locally:
`2017/04/01 14:59:25 http.go:29: FATAL: could not parse "127.0.0.1:4180": parse 127.0.0.1:4180: first path segment in URL cannot contain colon`
Update: the above error happens as of go 1.8. This PR removes parsing via `url.Parse` and parses the scheme manually.
=> Fix url parse error

dist.sh, version.go
30% release binary size reduction - from 10487848 bytes to 7041472 bytes for the linux x86_64 build.
I also bumped the version for dev, I can rebase and omit that commit if a different version bump is done in master.
=> dist.sh: use go build option to strip binaries

providers/github.go
The use of the `access_token` GET query parameters when making api calls to github increases the possibility of accidentally logging the full text access token; since github supports passing these tokens via header it makes sense to do that, prevents the rick of disclosure and removes the need for a `tokenStrip()` method.
=> [github provider] use Authorization header, not access_token query parameter

README.md
"Enable and manage APIs" is now called "API Manager"
=> Update Google Auth Provider instructions

README.md
Current code is using URLEncoding but example was using the
standard RFC 4648 encoding. Switch to using the URL
encoding in the example as well.
=> Update cookie generation to match base64 encoding

options.go, options_test.go
When used solely for auth_request there is no upstream.
Instead of forcing users to set a dummy upstream, remove
the check.
=> Remove check for >0 upstreams

options.go
fixes #430 
Current master branch:
```
$ ./oauth2_proxy --upstream=127.0.0.1:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13b8d2f]
goroutine 1 [running]:
main.(*Options).Validate(0xc4200f8000, 0xc4200f8000, 0xc420012480)
/Users/pierce/go/src/github.com/bitly/oauth2_proxy/options.go:149 +0x30f
main.main()
/Users/pierce/go/src/github.com/bitly/oauth2_proxy/main.go:101 +0x1303
```
This branch:
```
$ ./oauth2_proxy --upstream=127.0.0.1:8080
2017/08/05 13:17:42 main.go:103: Invalid configuration:
missing setting: cookie-secret
missing setting: client-id
missing setting: client-secret
missing setting for email validation: email-domain or authenticated-emails-file required.
use email-domain=* to …
```
=> gracefully report un-parsed upstream URL

Godeps, README.md, main.go, options.go, providers/oidc.go, providers/providers.go
Takes over from https://github.com/bitly/oauth2_proxy/pull/165
Closes #332
cc @philips @gtaylor
See the README for usage with Dex or any other OIDC provider.
To test run a backend:
python3 -m http.server
Run dex and modify the example config with the oauth2 callback.
go get github.com/coreos/dex/cmd/dex
cd $GOPATH/src/github.com/coreos/dex
sed -i.bak \
's|http://127.0.0.1:5555/callback|http://127.0.0.1:5555/oauth2/callback|g' \
examples/config-dev.yaml
make
./bin/dex serve examples/config-dev.yaml
Then run the oauth2_proxy:
oauth2_proxy \
--oidc-issuer-url http://127.0.0.1:5556/dex \
--upstream http://localhost:8000 \
--client-id example-app \
--client-secret ZXhhbXBsZS1hcHAtc2VjcmV0 \
--cookie-secret foo \
--email-domain '*' \
--http-address http://127.0.0.1:5555 \
--redirect-url …
=> *: add an OpenID Connect provider

providers/gitlab.go, providers/gitlab_test.go
"read_user" works as a default scope for GitLab. The previous "api" scope gives full API access AFAIK?
=> Use read_user as default scope for GitLab

providers/oidc.go, templates.go
So that the login page doesn't say "Sign in with a  provider".
cc @ericchiang
=> Add OpenID Connect provider name.

README.md
Clarify that GitHub team slug name should be used for the `-github-team` configuration option.
=> Clarify that GitHub team option in README

Godeps, api/api_test.go, cookie/cookies_test.go, env_options_test.go, htpasswd_test.go, oauthproxy_test.go, options_test.go, providers/azure_test.go, providers/gitlab_test.go, providers/google_test.go, providers/internal_util_test.go, providers/linkedin_test.go, providers/provider_default_test.go, providers/session_state_test.go, templates_test.go
This PR closes out https://github.com/bitly/oauth2_proxy/issues/474 by swapping out the deprecated `bmizerany/assert` package in favor of `stretchr/testify/assert`.
=> Swap out bmizerany/assert package in favor of stretchr/testify/assert

README.md, oauthproxy.go
The Cookie Prefixes spec disallows the use of the `domain` attribute in cookies
if the `__Host-` prefix is used
(https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00#section-3.2).
There's no need to set it to the host by default, so make it optional. If it is
set to a non-empty value, still output a warning if it is not a suffix of the
host, as that's likely not wanted.
Fixes #352.
=> Don't set the cookie domain to the host by default, as it breaks Cookie Prefixes

README.md, providers/gitlab.go, providers/gitlab_test.go
This PR fixes https://github.com/bitly/oauth2_proxy/issues/441
https://docs.gitlab.com/ce/api/README.html
`API requests should be prefixed with api and the API version. The API version is defined in lib/api.rb. For example, the root of the v4 API is at /api/v4.`
=> providers: update gitlab api endpoint to use latest version, v4

Godeps, oauthproxy.go, oauthproxy_test.go, options.go
Since I'm no longer with 18F, I've re-released hmacauth under the ISC license as opposed to the previous CC0 license. There have been no changes to the hmacauth code itself, and all tests still pass.
=> Switch from 18F/hmacauth to mbland/hmacauth

options.go, options_test.go
This is a follow-up PR to close out https://github.com/bitly/oauth2_proxy/pull/387 . Part of that PR was actually closed out by https://github.com/bitly/oauth2_proxy/pull/431 but we missed adding in some tests for it there so going to do it here.
* don't add in failed compiled regexes for skip auth regex option
* improve test coverage for skip auth regex option to handle partial
success case
* add tests for incorrect upstream options parsing errors
=> options: update options parsing for better handling of incorrect values

oauthproxy.go, providers/github.go, providers/github_test.go, providers/provider_default.go, providers/providers.go, providers/session_state.go, providers/session_state_test.go
Hi,
with this PR I try to fix https://github.com/bitly/oauth2_proxy/issues/438
The main change is saving both SessionState's Email and User in session, so that they can be used later.
Moreover, a new function GetUserName has been added to the Provider interface to get User value when not equal to Email's local-part. Currently the only Provider that implements it is the GitHub one, for the others, a default implementation has been added to provider_default.go. For backward compatibility, User's value falls back to Email's local-part when empty.
Please, let me know if I can do anything to improve this PR.
=> GitHub use login as user

README.md, dist.sh
This PR closes out https://github.com/bitly/oauth2_proxy/issues/479 by:
* creating a sha256sum.txt file containing sha256 checksums for each pre-built binary that we distribute with our releases. we'll have to attach this file to each release manually for now. we may or may not want to commit this file into the repo in the future, but for now this should be a good start.
* updates our README.md file with some instructions on how to verify pre-build binaries using the sha256sum.txt file we provide.
=> distribution: create sha256sum.txt file when creating version releases

README.md, logging_handler.go, logging_handler_test.go, main.go, options.go
We want to analyze access logs of the oauth2 proxy in our centralized logging system where we use a slightly different access log format.
This PR makes the request logging format configurable via a template string passed as `-request-logging-format`. The default format stays the same of course.
=> Make Request Logging Format Configurable

README.md
Nginx never sends the body with the auth_request sub-request, but
keeps the original Content-Length header by default. Without some
config tweaks, this results in the request to /oauth2/auth hanging.
fixes #442
=> README: fix nginx auth_request example for requests with body

oauthproxy.go
default domain changed from request Host to blank, recently
try to clear cookies for both
The combination of #466 and #376 causes this problem where the cookie which could not be parsed also was not cleared, and login never worked:
```
2017-12-12 23:47:54.321 oauthproxy.go:608: 127.0.0.1:49562 ("158.106.212.130") could not decode session state: expected 2 chunks got 1
2017-12-12 23:47:56.665 github.go:178: Found Github Organization:"PhysicalGraph" Team:"platform-video-pizza-box" (Name:"Platform: Video Pizza Box")
2017-12-12 23:47:56.766 github.go:239: got 200 from "https://api.github.com/user/emails" [{"email":"pierce.lopez@gmail.com","primary":true,"verified":true,"visibility":"public"},...]
2017-12-12 23:47:56.882 github.go:288: got 200 from "https://api.github.com/user" …
```
=> more robust ClearSessionCookie()

providers/google.go
This provider used to allow padding, until it was switched to the builtin RawURLEncoding. This PR fixes the regression by accepting padding again via throwing the padding away.
Google doesn't include padding, but other OAuth2 servers may, and this provider is the default when using a custom provider.
=> Strip JWT base64 padding before parsing. #560

README.md
Hi @apriendeau,
In your [post](https://github.com/bitly/oauth2_proxy/issues/628#issuecomment-456909589) you mentioned pomerium as an alternative to oauth2_proxy but PR #684 didn't include it.
Would you mind merging this PR which adds [pomerium](https://github.com/pomerium/pomerium)?
Thanks!
=> docs: add pomerium
