contrib/google_auth_proxy.cfg.example
main.go
oauthproxy.go
options.go

Add flag to enable/disable cookie's HttpOnly flag.

---

oauthproxy.go
options.go

This is just being picky, but gofmt kept complaining about these files, so made a separate PR with the whitespace fixes in.

Run gofmt over source

---

README.md
contrib/google_auth_proxy.cfg.example
main.go
oauthproxy.go
options.go
templates.go

This adds the ability to specify a directory with custom sign in and error templates.
This fixes: #11 #15 #55

Custom Sign In Template Support

---

oauthproxy.go

When you visit the sign-in page, fix it's ability to clear cookies (was missing the secure flag).

clear cookie fix

---

main.go
version.go

Having the releases is really nice. Unfortunately, while using 1.0 I was bit by https://github.com/bitly/google_auth_proxy/pull/40. Any chance of getting a bug fix release?

Cut a new release

---

README.md
api/api.go
main.go
oauthproxy.go
oauthproxy_test.go
options.go
providers/github.go
providers/google.go
providers/google_test.go
providers/internal_util_test.go
providers/linkedin.go
providers/linkedin_test.go
providers/myusa.go
providers/myusa_test.go
providers/provider_data.go
providers/provider_default.go
providers/providers.go

cc: @intellectronica as you had a similar work inprogress

Add Github Provider

---

.travis.yml
README.md
contrib/oauth2_proxy.cfg.example
dist.sh
main.go
oauthproxy.go
oauthproxy_test.go
options.go
version.go

A bunch of awesome changes have landed since v1.1. It's time to start the ball rolling on a v2.0.
Since this release includes the project name change, there will be various other backwards incompatible changes included.

Release Version Two

---

README.md
main.go
oauthproxy.go
oauthproxy_test.go
options.go

For tools that don't like empty passwords, this change allows
one to set a shared secret password for all users.

Add support for setting the basic auth password.

---

README.md

@jehiah ready for review - the auth token generation flow has changed a little, mostly for the better.

Google auth configuration screen flow has changed

---

main.go
oauthproxy.go
oauthproxy_test.go
options.go
options_test.go
providers/github.go
providers/google.go
providers/google_test.go
providers/internal_util.go
providers/internal_util_test.go
providers/linkedin.go
providers/linkedin_test.go
providers/myusa.go
providers/myusa_test.go
providers/provider_data.go
providers/provider_default.go

Various changes to make the proxy more inline with Go coding style for naming. See commits for details.

Go code style

---

README.md

Google changed to developer console UI, updated walkthrough to match new UI.

Google UI changes

---

contrib/oauth2_proxy.service.example

Since most people want to run this as a service, having some sort of an
example file is very useful to have.

Added SystemD example service file

---

README.md
api/api.go
providers/facebook.go
providers/providers.go

This adds the abilibity to get email address via FB auth.
cc: @pregiotek

Facebook auth Provider

---

.travis.yml

Bump the latest patch release.
Cheers

Bump travis version

---

oauthproxy.go

Implement a /sign_out endpoint that signs the user out (by clearing cookies).
This fixes #306

[signout] Implement logout endpoint

---

.travis.yml
Godeps
oauthproxy_test.go

In preparation for a release, this updates the vendored dependencies.

Update vendored dependencies.

---

.travis.yml
README.md
version.go

Release v2.2

---

README.md

Simplified, then added cookie handling. See commit messages for some rationale.
Any opinions @semenko @ashkulz ?

README: nginx auth_request example updates

---

providers/internal_util.go

strip all log statements with the endpoint var

strip all tokens

---

oauthproxy.go
oauthproxy_test.go

nginx auth_request: fix -skip-provider-button

---

providers/google.go

use base64.RawURLEncoding.DecodeString() in place of a bespoke function

raw url encoding

---

Gopkg.lock
Gopkg.toml
htpasswd.go
htpasswd_test.go
main.go

Fixes #404 (at least partially)

Support bcrypt passwords in htpasswd
